### ISSUE TITLE
does not persist logs across sessions

### ISSUE THREAD

**Issue by andreasn** [flathub/org.gnome.Polari#5]
It seems that logs do not persist across sessions (like for example when I have to reboot my machine to apply OS updates).
~/.var/app/org.gnome.Polari/data is supposed to have a TPLogger folder, but it doesn't seem to be there.

**Comment by fmuellner** [comment]
> ~/.var/app/org.gnome.Polari/data is supposed to have a TPLogger folder

No, the logs are expected in the regular ~/.local/share/TpLogger folder, for various reasons:
 - not lose "pre-flatpak" logs
 - still work when telepathy-logger is running unsandboxed

What's the output of
```sh
$ flatpak run --command=ls org.gnome.Polari -ld .local/share/TpLogger
```
We used to rely on telepathy-logger on the host, so only request read-only access to the logs. However that was [addressed a while ago](https://gitlab.gnome.org/GNOME/polari/commit/be50eeecc56), so it shouldn't be the issue here.

**Comment by andreasn** [comment]
This is what I get:
`ls: cannot access '.local/share/TpLogger': No such file or directory`
Version is 3.30.2

**Comment by fmuellner** [comment]
Oh, I may have an idea what's going on. The folder doesn't exist outside the sandbox either, does it?

**Comment by andreasn** [comment]
Indeed, it doesn't.

**Comment by fmuellner** [comment]
Can you please try the test build in the pull request?

**Comment by fmuellner** [comment]
Some testing suggests that the patch indeed fixes the issue. I therefore went ahead and included it in the 3.31.91 release, which is also available in the flathub beta channel.

Can you confirm that either the build for this PR or the beta version is working for you now?

**Comment by andreasn** [comment]
Tested 3.31.91 and now it works! Thank you!

**Comment by fmuellner** [comment]
Awesome, pushed the fix to stable as well then.
